### ISSUE TITLE
Subtitle is using `camelCase` as `subTitle` in Messages created on portal

### ISSUE THREAD

**Issue by bardram** [cph-cachet/carp-portal#23]
It should be `snake_case` for consistency to all properties.
 
See issues >> https://github.com/cph-cachet/carp.sensing-flutter/issues/434

**Comment by SufyaanKhateeb** [comment]
I can work on this.

**Comment by pavliuc75** [comment]
the announcements are stored in the documents/data table in the db. The column is jsonb and data is persisted as it was received from frontend without modifications (so data received from study app would be saved with "sub_title", while data received from portal would be saved as "subTitle"). Since announcement are only used in dev, it was decided to not make any migrations to already persited data. Instead we just modify the portal to also send the data as "sub_title" for consistency.
